apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awesome-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "awesome-chart.name" . }}
    helm.sh/chart: {{ include "awesome-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "awesome-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "awesome-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.containerHostname }}
      hostname: {{ .Values.containerHostname }}
    {{- end }}
      containers:
        - name: {{ include "awesome-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 -}}
          env: 
          {{- range $i, $env := .Values.env }}
            - name: {{ $env.name }}
            {{- if eq $env.type "secret" }}  
              valueFrom: 
                secretKeyRef: 
                  name: {{ include "awesome-chart.fullname" $ }}
                  key: {{ $env.name }}
            {{- else if eq $env.type "plain" }}
              value: {{ $env.value }}
            {{- end }}
          {{- end }}  
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.persistence }}
        {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "awesome-chart.fullname" . }}-data
              readOnly: false
        {{- end }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.persistence }}
    {{- if .Values.persistence.enabled }}
      volumes:
      - name: {{ include "awesome-chart.fullname" . }}-data
        persistentVolumeClaim:
          claimName: {{ include "awesome-chart.fullname" . }}-data
    {{- end }}
    {{- end }}