{{- define "get-secrets-from-env-list" -}}
    {{- $allenv := index . 0 -}}
    {{- range $i, $scrts := $allenv -}}
        {{- if eq $scrts.type "secret" -}}
            {{- nindent 0 $scrts.name -}}: {{ "change_me" | b64enc -}}
        {{- end -}}
    {{- end -}}
{{- end -}}

{{ $secrets := include "get-secrets-from-env-list" (list .Values.env ) }}

{{- if gt (len $secrets) 0 -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "awesome-chart.fullname" $ }}
  labels:
    app.kubernetes.io/name: {{ include "awesome-chart.name" $ }}
    helm.sh/chart: {{ include "awesome-chart.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  {{- nindent 2 $secrets -}}
{{- end -}}
